
# Core Canvas
background            #000000
foreground             #8b75d9

selection_background  #000000
selection_foreground   #8b75d9


# Cursor definition
cursor                #8b75d9
cursor_text_color     #000000

# Window layout borders (matches your active purple underline)
active_border_color   #8b75d9
inactive_border_color #1a1a24

# The 16-Color ANSI Matrix (Syntax Highlighting)
# Black (Dull Void / Bright Gray)
color0  #15161e
color8  #44444a

# Red (Eldritch Crimson)
color1  #f7768e
color9  #ff8b9e

# Green (Void Slime / Acid)
color2  #00f1c3
color10 #33ffd8

# Yellow (Cosmic Decay / Gold)
color3  #e0af68
color11 #ffca7f

# Blue (Deep Abyssal Ocean)
color4  #565f89
color12 #7aa2f7

# Magenta (Your Shadow Violet Focus)
color5  #8b75d9
color13 #bdaeff

# Cyan (Ethereal Mist)
color6  #7dcfff
color14 #a4e5ff

# White (Starlight Dust)
color7  #a9b1d6
color15 #c0caf5
mark1_foreground #171928
mark1_background #f9515d

# Splits/Windows
active_border_color #a48cf2
inactive_border_color #171928

