
general {
    lock_cmd = pidof hyprlock || hyprlock --quiet
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600  -- Lock the screen after 10 minutes
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900  -- Turn off the screen after 15 minutes
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800 -- Suspend the system after 30 minutes
    on-timeout = systemctl suspend
}
