-- #######################################################################################
-- AUTOGENERATED HYPR CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

--
-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
--

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@60.00800",
	position = "0x0",
	scale = "1.00",
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
--###PROGRAMS###
local terminal = "kitty"
local browser = "zen"
local volume = "pavucontrol"
-- background
-- Execute your favorite apps at launch
--exec-once = garuda-welcome
--exec-once = $terminal
-- Add networkmanager applet to tray in waybar
-- Set keyboard layout
--exec-once = .local/bin/garuda-locale.sh

-- Set monitor values. For own values, please comment with #
--exec-once = .local/bin/mon.sh

-- Source a file (multi-file configs)
-- source = ~/.config/hypr/myColors.conf

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 7,
	bezier = "myBezier",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 7,
	bezier = "default",
	style = "popin 80%",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 10,
	bezier = "default",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 7,
	bezier = "default",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 6,
	bezier = "default",
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("nwgbar"))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + SHIFT + code:65", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("wofi --normal-window --show drun --allow-images"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("nwg-drawer -mb 10 -mr 10 -ml 10 -mt 10"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("env MOZ_ENABLE_WAYLAND=1 " .. browser))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(terminal .. " --hold --directory /home/bfoster/config -e tv"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("warp-terminal"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("showmethekey-gtk -k -A"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("sniffnet"))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind("ALT + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("ALT + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("ALT + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("ALT + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("ALT + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("ALT + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("ALT + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("ALT + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("ALT + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("ALT + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.layer_rule({
	match = { namespace = "waybar" },
	blur = true,
	ignore_alpha = 0,
})

hl.bind("code:122", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"))
hl.bind("code:123", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"))
hl.bind("code:121", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ 0%"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("firedragon"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("code:232", hl.dsp.exec_cmd("brightnessctl -c backlight set 5%-"))
hl.bind("code:233", hl.dsp.exec_cmd("brightnessctl -c backlight set +5%"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("killall -9 wpaperd && wpaperd &"))

hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp)" - | swappy -f -'))
hl.bind("CTRL + Print", hl.dsp.exec_cmd(".config/hypr/scripts/screenshot_window.sh"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(".config/hypr/scripts/screenshot_display.sh"))

hl.bind(mainMod .. " + R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
	hl.bind("right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
	hl.bind("L", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
	hl.bind("left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
	hl.bind("H", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
	hl.bind("up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
	hl.bind("K", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
	hl.bind("down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })
	hl.bind("J", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })

	hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

hl.layer_rule({
	match = { namespace = "wofi" },
	blur = true,
})

hl.layer_rule({
	match = { namespace = "thunar" },
	blur = true,
})
hl.layer_rule({
	match = { namespace = "gedit" },
	blur = true,
})

hl.layer_rule({
	match = { namespace = "gtk-layer-shell" },
	blur = true,
})

hl.layer_rule({
	match = { namespace = "catfish" },
	blur = true,
})

hl.window_rule({
	match = {
		float = 1,
	},
	opacity = "0.85 0.85",
})

hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))

hl.bind("code:172", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("code:171", hl.dsp.exec_cmd("playerctl next"))
hl.bind("code:173", hl.dsp.exec_cmd("playerctl previous"))

hl.window_rule({
	match = {
		class = "^(one.alynx.showmethekey)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(showmethekey-gtk)$",
	},
	float = true,
	pin = true,
})

hl.window_rule({
	match = {
		class = "^(one.alynx.showmethekey)$",
	},
	size = "100% 5%",
	move = "0% 95%",
	border_size = 0,
})

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		numlock_by_default = true,
		follow_mouse = 1,
		touchpad = {
			natural_scroll = true,
			tap = enabled,
			disable_while_typing = true,
		},
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
	},
	general = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		gaps_in = 5,
		gaps_out = 10,
		border_size = 2,
		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(8f00ffee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
	},
	--decoration {
	-- See https://wiki.hyprland.org/Configuring/Variables/ for more
	--   rounding = 10
	--  blur {
	--    enabled = true
	--   size = 5
	--  passes = 1
	--}
	--drop_shadow = true
	--shadow_range = 4
	--shadow_render_power = 3
	--col.shadow = rgba(1a1a1aee)
	--}
	animations = {
		enabled = true,
		-- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
	--master {
	-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
	--   new_is_master = true
	--}
	gestures = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		-- workspace_swipe = on
	},
	misc = {
		disable_hyprland_logo = false,
	},
	-- Example per-device config
	-- See https://wiki.hyprland.org/Configuring/Keywords/
	-- executing for more
	--device:epic mouse V1 {
	--   sensitivity = -0.5
	--}
	-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
	-- Example windowrule v1
	-- windowrule = float, ^(kitty)$
	-- Example windowrule v2
	-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
	-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
	-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
	--bind = $mainMod, 36, exec, $terminal
	--bind = $mainMod, T, exec, $terminal
	-- Mainmod + Function keys
	--bind = $mainMod, F1, exec, zen
	--bind = $mainMod, F2, exec, thunderbird
	--bind = $mainMod, F3, exec, thunar
	--bind = $mainMod, F4, exec, nvim
	--bind = $mainMod, F5, exec, github-desktop
	--bind = $mainMod, F6, exec, gparted
	--bind = $mainMod, F7, exec, inkscape
	--bind = $mainMod, F8, exec, blender
	--bind = $mainMod, F9, exec, meld
	--bind = $mainMod, F10, exec, joplin-desktop
	--bind = $mainMod, F11, exec, snapper-tools
	--bind = $mainMod, F12, exec, galculator
	-- Move focus with mainMod + arrow keys
	-- Switch workspaces with mainMod + [0-9]
	-- Move to workspace with focused container with ALT + SHIFT + [0-9]
	-- Move active window to a workspace with mainMod + SHIFT + [0-9]
	-- Scroll through existing workspaces with mainMod + scroll
	-- Move/resize windows with mainMod + LMB/RMB and dragging
	-- status bar
	-- set volume (laptops only and may or may not work on PCs)
	-- other bindings
	--bind = $mainMod SHIFT, F, fakefullscreen
	-- Screenshots:
	--
	-- Change to swappy https://github.com/jtheoof/swappy
	-- Old functions only commented out to make it easier for the user to change if necessary.
	-- Snip a selection and pipe to swappy
	-- Screenshot a window and pipe to swappy
	-- Screenshot the current display and pipe to swappy
	-- https://github.com/hyprwm/contrib/blob/main/grimblast/grimblast.1.scd
	-- Print: All outputs
	-- SHIFT+Print: Select area
	-- $mainMod+Print: Current window
	-- $mainMod+Shfit+Print: Current output
	--
	-- bind = ,Print, exec, grimblast save screen && notify-send Screenshot captured
	-- bind = SHIFT, Print, exec, grimblast save area && notify-send Selected\ area captured
	-- bind = $mainMod, Print, exec, grimblast save active && notify-send Active\ window captured
	-- bind = $mainMod SHIFT, Print, exec, grimblast output active && notify-send Output captured
	-- for resizing window
	-- will switch to a submap called resize
	-- will start a submap called "resize"
	-- sets repeatable binds for resizing the active window
	-- use reset to go back to the global submap
	-- will reset the submap, meaning end the current one and return to the global one
	-- to move window
	-- other blurings
	-- window rules
	--windowrule = opacity 0.85 override 0.85 override,^(thunar)$
	--windowrule = stayfocused, ^(wofi)$
	-- window rules with evaluation
	-- exec-once = foot --server
	-- experimental(might work might won't)
	-- pre executions (under development)
	-- Clipboard Manager
	-- video play paues bindings
	-- Make the showmethekey windows float and pin them on touchpad
	--
	-- Let the user customize this hyprstart script by overriding stuff in $hyprstart
})

hl.on("hyprland.start", function()
	hl.exec_cmd("wpaperd &")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("nm-applet --indicator &")
	hl.exec_cmd("waybar")
	hl.exec_cmd("mako")
	hl.exec_cmd("exec xrdb -load ~/.Xresources")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
