# Preload wallpapers
preload = /home/bfoster/config/configs/user/hypr/backgrounds/Fuji-Dark.png
preload = /home/bfoster/config/configs/user/hypr/backgrounds/Fuji-Dark.png

# Set wallpapers
wallpaper = Monitor1,/home/bfoster/config/configs/user/hypr/backgrounds/Fuji-Dark.png
# Use an empty monitor name for a default fallback
wallpaper = ,/home/bfoster/config/configs/user/hypr/backgrounds/Fuji-Dark.png

# Enable/disable splash text
splash = false
