name: Configuration Test

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build Development Environment
        run: sudo nixos-rebuild switch --flake github:at-home-admin/nixosconfig#EXILE --show-trace

      - name: Run Tests
        run: nix -L flake check
