name: Update Flake Lockfile
on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight
  workflow_dispatch: # Allows manual trigger from the GitHub web UI

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: gh pr merge --auto --rebase "${{ steps.update.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.update.outputs.pull-request-number != '' }}

      - name: Send Gotify Notification
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: "${{ secrets.gotify_api_base }}"
          gotify_app_token: "${{ secrets.gotify_app_token }}"
          notification_title: "Build Successful"
          notification_message: "Your NixOS Flake was updated successfully!"
