name: Update Flake Lockfile
on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight
  workflow_dispatch: # Allows manual trigger from the GitHub web UI

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Update flake.lock
        run: nix flake update

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "YARARA BUILD - automated flake update"

      - name: Send Gotify Notification
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: "${{ secrets.gotify_api_base }}"
          gotify_app_token: "${{ secrets.gotify_app_token }}"
          notification_title: "Build Successful"
          notification_message: "Your build was completed successfully!"
